import Head from 'next/head'
import { FaFacebook, FaTwitter, FaInstagram, FaYoutube, FaSnapchatGhost } from 'react-icons/fa';
import { AiOutlineMail } from 'react-icons/ai';

export default function Home() {
  return (
    <>
      <Head>
        <title>Celtics Tailwind</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <h1 className="text-9x1">Teste</h1>
      <p className="text-4xl text-green-900 font-bold">Testeando</p> */}

      <header className="flex justify-between mx-auto p-1.5 border-green-600 border-b-2 items-center">
        <div className="flex w-2/12 sm:w-2/12 md:w-1.5/12 lg:w-1/12 xl:w-1/12 ml-4">
          <img className="w-1/2" src="/celtics-logo.png" alt="Logo Celtics" />
        </div>
        <div className="flex justify-end">
          <FaFacebook className="mx-1.5 text-xl text-green-600 cursor-pointer pointer-events-auto hover:text-green-900" />
          <FaTwitter className="mx-1.5 text-xl text-green-600 cursor-pointer pointer-events-auto hover:text-green-900" />
          <FaInstagram className="mx-1.5 text-xl text-green-600 cursor-pointer pointer-events-auto hover:text-green-900" />
          <FaYoutube className="mx-1.5 text-xl text-green-600 cursor-pointer pointer-events-auto hover:text-green-900" />
          <FaSnapchatGhost className="mx-1.5 text-xl text-green-600 cursor-pointer pointer-events-auto hover:text-green-900" />
          <AiOutlineMail className="mx-1.5 text-xl text-green-600 cursor-pointer pointer-events-auto hover:text-green-900" />
        </div>
      </header>

      <main className="flex flex-wrap">
        <header className="flex flex-wrap mx-auto w-11/12 bg-green-600 mt-6 p-6">
          <h1 className="flex flex-grow text-white font-bold">CELTICS AND TD GARDEN ARE WELCOMING FANS BACK</h1>
          <p className="flex flex-grow text-white">A limited number of fans may now be in attendance at Celtics home games. See how we’ve prepared to create a safe and healthy game experience.</p>
          <button className="bg-white flex-grow sm:flex-grow-0 p-1 sm:mr-2 rounded-md mt-2">PLAY IT SAFE GUIDELINES & PROTOCOLS</button>
          <button className="bg-white flex-grow sm:flex-grow-0 p-1 rounded-md mt-2">INTERESTED IN TICKETS?</button>
        </header>

        <section className="grid grid-cols-3 w-11/12 mx-auto">
          <article className="flex flex-wrap w-11/12 mx-auto my-3 border-green-600 border-b-2 pb-1">
            <div className="flex">
              <img className="rounded-md" src="/celtics-1.jpg" alt="Celtics 1" />
            </div>
            <h1 className="flex flex-grow text-green-600 text-lg font-bold">Celtics com força máxima contra os Nets</h1>
          </article>
          <article className="flex flex-wrap w-11/12 mx-auto my-3 border-green-600 border-b-2 pb-1">
            <div className="flex">
              <img className="rounded-md" src="/celtics-2.jpg" alt="Celtics 1" />
            </div>
            <h1 className="flex flex-grow text-green-600 text-lg font-bold">Celtics vencem os Bulls com tranquilidade</h1>
          </article>
          <article className="flex flex-wrap w-11/12 mx-auto my-3 border-green-600 border-b-2 pb-1">
            <div className="flex">
              <img className="rounded-md" src="/celtics-3.jpg" alt="Celtics 1" />
            </div>
            <h1 className="flex flex-grow text-green-600 text-lg font-bold">Celtics com força máxima contra os Nets</h1>
          </article>
          <article className="flex flex-wrap w-11/12 mx-auto my-3 border-green-600 border-b-2 pb-1">
            <div className="flex">
              <img className="rounded-md" src="/celtics-4.jpg" alt="Celtics 1" />
            </div>
            <h1 className="flex flex-grow text-green-600 text-lg font-bold">Celtics com força máxima contra os Nets</h1>
          </article>
          <article className="flex flex-wrap w-11/12 mx-auto my-3 border-green-600 border-b-2 pb-1">
            <div className="flex">
              <img className="rounded-md" src="/celtics-5.jpg" alt="Celtics 1" />
            </div>
            <h1 className="flex flex-grow text-green-600 text-lg font-bold">Celtics vencem os Bulls com tranquilidade</h1>
          </article>
          <article className="flex flex-wrap w-11/12 mx-auto my-3 border-green-600 border-b-2 pb-1">
            <div className="flex">
              <img className="rounded-md" src="/celtics-6.jpg" alt="Celtics 1" />
            </div>
            <h1 className="flex flex-grow text-green-600 text-lg font-bold">Celtics com força máxima contra os Nets</h1>
          </article>
        </section>
      </main>
    </>
  )
}
