import Head from 'next/head'


export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className="text-9x1">Teste</h1>
      <p className="text-4xl text-green-900 font-bold">Testeando</p>
    </>
  )
}
